# vim: set ft=yaml ts=2 sw=2 et :
---

name: build image

"on":
  - push

env:
  http_proxy: http://localhost:3142

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      apt-cacher-ng:
        image: sameersbn/apt-cacher-ng
        ports:
          - "3142:3142"
        volumes:
          - /acng:/var/cache/apt-cacher-ng

    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: sudo apt -y install debos debian-archive-keyring

      - uses: actions/cache@v2
        with:
          key: acng
          path: |-
            /acng

      - name: bootstrap
        run: sudo debos --disable-fakemachine --scratchsize=8G --environ-var=http_proxy:$http_proxy 01-bootstrap.yaml

