# vim: set ft=yaml ts=2 sw=2 et :
---

name: build image

"on":
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: sudo apt -y install debos debian-archive-keyring

      - name: bootstrap
        run: sudo debos --disable-fakemachine --scratchsize=8G 01-bootstrap.yaml

      - name: install base system
        run: sudo debos --disable-fakemachine --scratchsize=8G 02-base.yaml

      - name: install plasma
        run: sudo debos --disable-fakemachine --scratchsize=8G 03-plasma.yaml

      - name: finalize image
        run: sudo debos --disable-fakemachine --scratchsize=8G 04-image.yaml

      - name: create block map
        run: bmaptool create image.img > image.img.bmap

      - uses: actions/upload-artifact@v2
        with:
          name: image.img
          path: image.img

      - uses: actions/upload-artifact@v2
        with:
          name: image.img.bmap
          path: image.img.bmap

